# Generated by Django 4.0.5 on 2022-07-20 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phonecode', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=30)),
                ('categories', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=1000)),
                ('statec', models.CharField(max_length=50)),
                ('lga', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=1000)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
